
replicas: 4

configmap:
  data:
    BG_COLOR: '#3311DD'
    CUSTOM_HEADER: 'This is on the PROD environment!'

sealedsecrets:
  mysecret:
    foo: AgB37FYn+dxHXHNG0qJ2RS9aYbTNRpL00V6U4Pd5wDSp8HmAwkRrA65fVajacmcBZ2J/kEbsQeiupZKGZmlfbntZZboThsS0WEzHNBZM7Ylrrh/5vZHhxamY4QTybnWnuh6lmFBYOEDdrGExTKYHxhWaxAE59SAFAeaTo94wU755GrR/HsnQd55bH+PfUIUIc3ZBp4HrGKWyFL16Oz7cnQ497Opy/E9QjY1t0hWQV1TWvgmYzXYZ59bIxczfmrt26tJXkiIbHZPQWNJDKvfbcFAud9fKrgauz4iTHpS1rjYCgFzD4bbuZUU0yCcM9b1qXTZressqpbxnJSGOttNFSaxUWtwBj6XXDulyZQiLUjm6ohYLOvowEGMPxMR3zeHpZ+VmFwHgvp6aO40Y0Xq/uPl5mZFXnHvrpz0MEYh2vyH/ywTwx6ZOao8Ea16nR0P52ljO9/4N5ne/v1qzkrMr+sidueRXrysn7pUx4uDYYClfLlteLMSiNnoHzntSV3lkIHSRmLnHLWunN2SdAYGndMcGTgguvuL5SWzt5sxJaW+Qyfjdm5AAtgOQFjQiXj2Uu9t/zZmm+NbGaeV+szpxJIlbfr5TzhcLlgwTvGqms46v61DJ5bWStA7sLN5fV8WxnuTrrVW/tTzERwAQRdVYLQwZ1B5nPHwR6l90ZCE8cpt+5WM0nE/0+390bMCzOLnzm4gqsPUfAAG5j9ZTIw==
