
replicas: 4

configmap:
  data:
    BG_COLOR: '#331111'
    CUSTOM_HEADER: 'This is on the PROD environment!'

sealedsecrets:
  mysecret:
    foo: AgBtPnd84lS1StCe49RZiWEmncbU5iQXpTwBZ5XFm0nJ/9wsoPjfwU2AtqBcO2Xob2/u+pCWrYhroTQX3OcxFMTGPQWyHsNvy4TNYGavFI2L7WFXsqLE3dltHGvCut8WppZQmwKTY2T4m0bayi+QQwbfDifaaQGVLV5sD/P3B1VnGfDeLuEbPqcn8Hm1+Fgh+VeqQQnKRO1Wf26bcOBqApb7ZfmGmGKbaMGAHL8vB4yl64EM5GMrHATB/60iU0DwbuajuvUpkycWRMZuj1DZUugdFwMR/W1FazvgZ0tgE8oJRfI58DiSbqVgdmynHGTsGF6lMTTLczxoU0ZqR3UiLUYUuA+BAh3WW8hP2syxj1mnfojYW64M3TVNJNyKssX4zXl9OOf/XASn9LjCP+xTaBAI4KdicLv0fm6xfzxvXKzWC3ZDK0D/+SzG3Ys/9RWFQJnbfi9eGRhOQQ9uli2VVv4IyMmGC9QZIcxRIhxAzHkTtGaOiEqQyUjrmSjYAn97+aUMUoH/mF5Pd6KwSOLcTK8yfnZYHphncUgbGwGgdnffYyTnQ+XHlpxftkkbYZ9yqtS8JbGoZl/D4Lamd5NAX2IThGEbIhGBnCWEXXraaj0kFstv/rw2qJufruRawr1QCPF2WIAREHktn2MCbkVlYO9O8LRPFADtbJBvUvaO8ai2H7I6MfbAJFOry4nZmbro6+0h6U2Ous4DiZR3aQ==
