
replicas: 2

configmap:
  data:
    CUSTOM_HEADER: 'This is on the DEV environment!'

sealedsecrets:
  mysecret:
    foo: AgAZTLv3OndNdtgdfZwL5jU4icnnPn5/kTyRchyhU3uqQ1vE9Mk/4sATaM+CZe45iqVSS2UaLKHpdq14H6cpRleBFuNzmT+/7fP6Gm3T6vXk8MC8m3O8xxXTOnyiMOciqojOIGqd34Cr0BZrDEgckdKrwLH9rsPR5Fga2QNki1iLDFKvw3I0MhASOwTRl2PeDvO5qyz7/WvRMdYFr1Lim3azu6ynKzohoU8QDZETTawfFHi8Atbhzo+4o2XXIz42JNKmZgZFqmChCfGwAHgQ8yNAPmwnQqQgQL5ZgMnCqSMuW6hnki6ytvoPlt5DCg09oE8WaLqP82W8UsGBCqGNceylRXeqftUJ5XQUyHhuvaAj0XPgVD8NdfUSQNdX4o3pZYQxNTAAE4K4VGJ7HWZ+Pekub/vcu/j/Ofo0oayyiwggRgQwhscjViI4mL3XWiDHjBdMtzLzZE1PilakUfV0H1D0X91wRlYYVTGp6VknXje12NIZjEOWu6baAU7pFOlEsGfqYhJd6xPuVwqvWuRq3e3Q+J9t7o3Yq4s8VP1ZNQfvRMvBl/nXPKfiWHzxEA2hqFHpdHU8qp3tp5UIrQIzlsb9+tCk1gCQKHTBheP/mvHxCag0z3yZLAQaKOnlj7cU/eJG8oS6wH71tD8JMsvjjsuZxD82FxJMTZlNDRfL0x7IohSYeVrR75RKmwjfalraFdEOuDzhctkWXGx/
