
replicas: 2

configmap:
  data:
    CUSTOM_HEADER: 'This is on the DEV environment!'

sealedsecrets:
  mysecret:
    foo: AgChIoCLRvAQF2nwuRAkYTSzlFe3Z2SxphHTfSArdeHsceT3M5c+2QyNjTNn2moCET2FOiE2IIsEOmVxwSRXDD9+UQa6Vsmd4o4/DbN8XSZLjNR99MlMvCkhLWVbQhPowyVwWqhavftQ4hj/qX/BXhFRCd1lQcXDurIHbUyyZ5sls4JLi1Oeb7pfQhXKB8So/ssOz3NdF0oTibWcyFfe+3hbXTNbBA2uI/MCy71ZMFupV618VIgEaY26YoxYJrmzGyZuEwctfyBweBqhEV6e79mXeRWMYGbgqvAJ3Ci/Jc2bAhh1jblodscZYEdfKzR2UU1ER2u0DnUODbTfDNXRzAZB93yWP6nZ1wGeXhRtgkr7vuJqRXJwv3Vz7W0EyIb+wBWAx9snYv68J9LXRbpjKOV417OmuDFK/OtMK1gDQD9Ccw53X2jo3kxHBQLHiQHttP26LXfAtmxjOyhg3Hl0lQeA6EvasdlEp1XYQWQMYvO5AWQQa4OkQa6H/Jj/qftxWATx0wQYMGAWZE4jG43TGFdmnooJAOA3JhBm5WuiNkJeu5XqLsm4/cFQsvlzm6siV3LxQAEgo6oe6ltdmxkVxzHsyCmjQqkGGphgF787VivmB7xDF3xpIjA0rIl6pYo0qiETEYV1uPj7CcJXrRGKQO/NUlZ/Ynuy7DAtHkKTZjluq4IvuVYxe9t9ItLV7tZTJ0HMe2hvfIkH2nWh+T+zpC0=
