
replicas: 2

configmap:
  data:
    CUSTOM_HEADER: 'This is on the DEV environment!'

sealedsecrets:
  mysecret:
    foo: AgCCgMp1zOcdWrE27rWT/iAK/rsXAz6gJhcgHNo6yRB7/oYBZt15lsXmkzBvKYEuF9CTalUsRPFKc1WXTAW5oNAuB18HQduSakfVlGc/7dO1WMt7udvp6lPhIy9LRZTR62s36Z0tr+V+8D29fzdaVKnx/Zz5kesJkLwY/oJ7f4EnvcWhI69D0GCdw9KZk1EcvqMJ0eOqCFNz78hzIIF32hyTLyuiMt5gukWxke3x2LKUlFfDRKVDe4tNid0zv4VPDZsjQYLEPk2F5whG6AuMCbdY9CWbmEWnJ/HaXAvqSQcGEiOLlr5GmtE2jtsZ5F2RTzDfx7zkV8VYmnVojuJQ1CsW1QWt/6LZEMWMIL5fCHzsguxUFiV4I70K5kPaJJRnpgy/8HnPKFERMRGjB2MwmHeQHvNgq5MoO+zYEgFbqfVjOIoGoxx7Eynt44IvDJ1wH7lHzwageZgPXQ2F17j2o8QhGdCHb97ob2QKMKDf2v+s/WWev+HPxQq4uSQ4rVl9u1IL1gpqa7W0BBqrmU2a+LREMM7zCADPLuQNuGx1nnYQcbAZ/a/0z+rLv/ImjqivklI33C2RzP3XFvEAacztZoiR925d4z2fjNpWBFfjMPcUrWovQniRzY16ppb7cCiLQRKSr17xREWVphIqKEzIzjRN+XAQz7yFOqh6WuxMSrFb/jkoBKKyAvdRhsk9VJgR7XqbDLnSBeQb+siH3A==
