
replicas: 4

configmap:
  data:
    BG_COLOR: '#3311DD'
    CUSTOM_HEADER: 'This is on the PROD environment!'

sealedsecrets:
  mysecret:
    foo: AgBpwK7pehjc9U8uowuVQ0MX4K8kDjY7d6i9H1ZxG2t8SPK3SEw/UuHGofoDf+B9yNZw7WpdgLt9sxlIvA2HUF92Zy+VZGsyCMmtaggQcVWz+6wI6UidX+RbxzyGf2xoxfyoUDOjaVCUw8ShfF/bhZuBwpg/zlg3Py4wsgrNUJeWZUaAD+kcab5b2OnWCHtNKPqcWsK/N2/Jp5DgXng3hLTWKT2jw00DIyiGSJvQlczax98nFmLnQ4lI1odsvBt/3CkbqipqCtGfdBklU2KnUeBNIJ7I1vJzPX7kn8kO5O+GYiGhMGDCv5KzXZ3I+IzVi9hH+eK0oFwGa2JYyUlRmxmNvrTnbpk9NgoRjKesUdgvYoL0Nh6CFLofaBR4yi3o2cNeliB9pf2wOa/tW/w2MNqOCxWG7sBUHP+44aYhb6jZxzVRfsVkoSPDiV67ShppIAeYWaaIaOeuWOow3JBd71p1NMCaS0j207JTh9xaOvXBt2YpZIKprr+jENEYb7FaW0vx6HCs24wHh4zTqa15B9WeaZoAUokL1C7pmBB3t+fr55IlMCxQwQyNv5++Ei065cc89Sgj2QQDrXwoDUEj52Yj2xSO2yUlMBKpl92Sw4g95yDX5f7PsVpn6S6S1GksjUTJUeJMCRehVngmYy0q6gl7PH/qLLz4S1fSiQylWk75n8xo0ABebFhKeWVyGzJQ19v6PL37exD8iTeQ16QBeiHo
