---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: webapp-prod
spec:
  encryptedData:
    foo: AgBi37SgCtZTfelH84RXnzFECzeVriS4lcPpj7LG8ehpMskFqkEnWk3xvfz5td1B4lMqtgmTADrCsPSrFn/yORovNVqBBNhAlg9mQV8sTVtCNy7u9DeZ61R6pUANLLMpCRonsbqphcPUtKDtW8VOrB7etUPFknvlmFgIDNMmSuM1ews7nvBFfywVGJqE8hdsgiBcHjcEdgCr9fDx2INREByF27fJYFrF/dnGaUjWynGordS3ZWQDhqsovtrVhV/0dzEEEuUxRiDwas8Xe+y0vexDWQn3ckNQ+iZmHiU/UYbl1AXQZyV7UbUud9FcPrEzTDddSHFQ5uQTsAkhhxI7NAJlwq9dJPM5Q5Gzx09YkJX/K6ly7N5ssPoJMmYevhti1yTv/tKsf11Lo/lwBxY2BhioPqwkRuouY5ohVxf6YO9J+4QETZdetbJBjF0zunE0Tz6K/5OIiNqJ0uFHyDyUFrIvEKqLVn0tNy/rRTsVwSOGK7Z58iy0Wl9QNhdeQlpS/YgzqmMp0TTUA9qgeZcUlATDYUldSMnBw+WRVz2WzcGCbSpwRifodBHByyiSlCgQhVuJC3S+xuG6c1gB89Ln+dJf4GmI7SFPM5N0Z9yPb3cfWiLUxuKYzY8+Krz6pv1T2Ia59yqK/IX5Mu5gsgPxUCv1yw+pXUdm1Sa2d5snpn7K4+BvfNm5dYe5RhbOJZAvmHnLQ3WCNuo=
  template:
    metadata:
      name: mysecret
      namespace: webapp-prod
