---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: webapp-prod
spec:
  encryptedData:
    foo: AgBF+7Oi61NKo/P7rzVVYdHtn/ZUya1cp5laihZTZXRf75rF3k1yVGAaTw4MjawvW+UDDoNiwVrNdNoMJXOARQwlL8D8ULSovAm8IvSclIQCdLMWAO3R/LR5huYQwis8KG64wQwO7k42IvUuYYX+GKBCcLS+6GEuwIGyR3nXfMZj9htgP6ojubMq9zvHuZu0tNgWAsd+WQszC6QkBnjPdBm3xYgvJJQAN1jMbgxPQg/CrFi4DUd4YGvq+0CkShPQPILQRsy1P1vX8jGCq8rN7LHagPh8hmlvjax2iL1/lMTpyrkbLbfYFpIK8cBWPm/nf3lUWI9OlpaYI4Ih24+iKgMSgrxRDdl1ZDQAwvbb6VOlovRu6ZiSQhYBuB0qEZF01s7XcZ0U3gMTRjviO8FPPDtyZiXM/GkwjqxfsEn0xZZ+Q2y6vKUUPJWH2AVPBBfmfDqxZsRDyNWtTr4eZbh2Ec9kqoOB8qIqSnV5aOLlC6LwjDdb8Sut2rdZ1lPKdJfn1147dUvFQxqydmxzFIYwnKclo4iyXML7XyPDhsnd/8LXmyff3VBesERSMDW0dd1FxcgY+bf3+R0jKq170wN3A87PWx07AhSf/n1a2r9FygXegN2r5pZ12Ou6YWUMErWiRSRQfjBxtxSaGgNClBjgYvJj3ZWCvtbUNaIDTu66wml3gFDNsDPEOzzij7sgQ8YFSZv7QQoh6zSkvlzTGHs=
  template:
    metadata:
      name: mysecret
      namespace: webapp-prod
